# Generated by Django 3.2 on 2021-05-12 18:42

from django.db import migrations, models
import tools.random_generate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=tools.random_generate.random_code, max_length=16, unique=True)),
                ('name', models.CharField(max_length=32)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/channel/')),
                ('is_verified', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(default=True)),
            ],
        ),
    ]
