# Generated by Django 3.2 on 2021-05-02 12:10

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(code='mismatch', message='Length must be 16', regex='^.{16}$')])),
                ('name', models.CharField(max_length=32)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='channel_avatars/')),
                ('is_verified', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('subscribers', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(default=True)),
                ('saved_playlists', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(8)], verbose_name='key'), blank=True, null=True, size=None)),
                ('saved_contents', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='mismatch', message='Length has to be 16', regex='^.{16}$')], verbose_name='key'), blank=True, null=True, size=None, verbose_name='favorites')),
                ('liked', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='mismatch', message='Length has to be 16', regex='^.{16}$')], verbose_name='key'), blank=True, null=True, size=None)),
                ('disliked', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='mismatch', message='Length has to be 16', regex='^.{16}$')], verbose_name='key'), blank=True, null=True, size=None)),
                ('subscribed', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='mismatch', message='Length has to be 16', regex='^.{16}$')], verbose_name='code'), blank=True, null=True, size=None)),
            ],
        ),
    ]
