# Generated by Django 3.2 on 2021-05-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_contents',
            field=models.ManyToManyField(blank=True, to='content.VideoContent'),
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_playlists',
            field=models.ManyToManyField(blank=True, to='content.Playlist'),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribed',
            field=models.ManyToManyField(blank=True, related_name='channel_subscribers', to='applications.Channel'),
        ),
    ]
