# Generated by Django 3.2 on 2021-05-03 19:10

import applications.models
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import tools.validators


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_channel_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='disliked',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='mismatch', message='Length has to be 16', regex='^.{16}$'), tools.validators.content_validation], verbose_name='key'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='mismatch', message='Length has to be 16', regex='^.{16}$'), tools.validators.content_validation], verbose_name='key'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='saved_contents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='mismatch', message='Length has to be 16', regex='^.{16}$'), tools.validators.content_validation], verbose_name='key'), blank=True, null=True, size=None, verbose_name='favorites'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='saved_playlists',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(8), tools.validators.playlist_validation], verbose_name='key'), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='profile',
            name='subscribed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(code='mismatch', message='Length has to be 16', regex='^.{16}$'), applications.models.channel_validation], verbose_name='code'), blank=True, null=True, size=None),
        ),
    ]
