# Generated by Django 3.2 on 2021-05-18 10:13

import django.contrib.postgres.fields
from django.db import migrations, models
import tools.random_generate


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameCopyright',
            fields=[
                ('key', models.IntegerField(default=tools.random_generate.random_key, primary_key=True, serialize=False)),
                ('is_allowable', models.BooleanField(default=True)),
                ('accept_monetization', models.BooleanField(default=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None)),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SongCopyright',
            fields=[
                ('key', models.IntegerField(default=tools.random_generate.random_key, primary_key=True, serialize=False)),
                ('is_allowable', models.BooleanField(default=True)),
                ('accept_monetization', models.BooleanField(default=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, null=True, size=None)),
                ('song', models.CharField(max_length=64)),
                ('artist', models.CharField(max_length=64)),
                ('album', models.CharField(max_length=64)),
                ('licensed_to', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Copyrights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_private', models.BooleanField(default=False)),
                ('is_adult_content', models.BooleanField(default=False)),
                ('is_kids_content', models.BooleanField(default=False)),
                ('game_copyrights', models.ManyToManyField(blank=True, to='additional.GameCopyright')),
                ('song_copyrights', models.ManyToManyField(blank=True, to='additional.SongCopyright')),
            ],
        ),
    ]
