# Generated by Django 3.2 on 2021-05-03 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('additional', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restrictions',
            options={'verbose_name': 'Content Restrictions', 'verbose_name_plural': 'Contents Restrictions'},
        ),
    ]
