# Generated by Django 3.2 on 2021-05-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20210513_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='contents',
            field=models.ManyToManyField(blank=True, to='content.VideoContent'),
        ),
    ]
