# Generated by Django 3.2 on 2021-05-13 17:53

from django.db import migrations, models
import tools.validators


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_playlist_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='short_videos',
        ),
        migrations.AddField(
            model_name='status',
            name='short_video',
            field=models.FileField(default=None, upload_to='statuses', validators=[tools.validators.validate_size, tools.validators.validate_extension]),
            preserve_default=False,
        ),
    ]
