# Generated by Django 3.2 on 2021-05-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20210513_2353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommunityContent',
        ),
    ]
